### ISSUE TITLE
Post Idea: Contributing 101

### ISSUE THREAD

**Issue by 0xTim** [vapor/blog#44]
Link to GH docs for forking and submitting a PR, link to help wanted/good first issues boards, discuss how the review process works, adding tests, how releases work and how the release notes are generated

Topics to cover:
* documentation
* translating the docs
* API docs
* bugs
* features (should be discussed first)
*

**Comment by BennyDeBock** [comment]
@0xTim I've seen this was added to the docs and a blog post was made for it. That means this issue can be closed right?

**Comment by 0xTim** [comment]
Yep!
