### ISSUE TITLE
Blog responses with content-type: binary/octet-stream

### ISSUE THREAD

**Issue by patricks** [vapor/blog#90]
My RSS Aggregator can't fetch the rss feed from: https://blog.vapor.codes/feed.rss because I always get the error that the content-type is: `binary/octet-stream`.
Shouldn't this be `application/rss+xml` (see: [https://stackoverflow.com/questions/595616/what-is-the-correct-mime-type-to-use-for-an-rss-feed](https://stackoverflow.com/questions/595616/what-is-the-correct-mime-type-to-use-for-an-rss-feed#595622))

**Comment by 0xTim** [comment]
Thanks for reporting! This is due to the way we deploy and serve the site. See #91 for the fix
